### ISSUE TITLE
Check AWS secret Access Key

### ISSUE THREAD

**Issue by PeterTough2** [phpandrew/php-sts-temp-credentials#1]
Hello,

I am trying to update your code to call `https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items` endpoint and retrieve stock quantity.

I added the code below at the bottom

```
$authorize_str = $headers[0];
$x_amz_date = $headers[3];
$x_host = $headers[1];

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items/?marketplaceIds=ATVPDKIKX0DER&includedData=summaries&locale=",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_SSL_VERIFYHOST => false,
  CURLOPT_SSL_VERIFYPEER => false,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_POSTFIELDS => "",
  CURLOPT_HTTPHEADER => array(
    "$authorize_str",
    "Content-Type: application/json",
    "$x_amz_date",
    "host:sellingpartnerapi-na.amazon.com",
    "user-agent: php-sts-temp-credentials",
    "content-type: application/x-www-form-urlencoded; charset=utf-8",
    "cache-control: no-cache"
  ),
));
```

But I get this error from the API

`"errors": [ { "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'GET /catalog/2022-04-01/items/ includedData=summaries&locale=&marketplaceIds=ATVPDKIKX0DER host:sellingpartnerapi-na.amazon.com x-amz-date:20230409T222811Z host;x-amz-date e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' The String-to-Sign should have been 'AWS4-HMAC-SHA256 20230409T222811Z 20230409/us-east-1/execute-api/aws4_request 2011ff1686ea70cd4054e7c781651243425d78188df80520143bce02d5d72d79' ", "code": "InvalidSignature" } ] }`

Can you show me how to implement this correctly.

Thanks.

**Comment by phpandrew** [comment]
@PeterTough2 in the following function, set debug = true
> calcualteAwsSignatureAndReturnHeaders()


Compare your string to the "The String-to-Sign should have been".

I will also review my script for any changes I may have made over the last bit.

**Comment by PeterTough2** [comment]
I have tried it already.

You can test your code with my credentials too, I want to be sure where the
problem is coming from.



Credentials

Login with Amazon Client Id (aka LWA Client Id):
amzn1.application-oa2-client.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Login with Amazon Client Secret (aka LWA Client Id):
amzn1.oa2-cs.v1.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS User Access Key ID (aka AWS UserId): AKIAQARTXIXXXXXXXXXXX
AWS User Secret Access Key (aka AWS SecretKey):
MpK1WMkY6Xd+wC5p5sckC61MaXXEDdedfeXSFD
AWS Role ARN (aka Role ARN):  arn:aws:iam::xxxxxxxxxxx:role/AssumeRole23

**Comment by phpandrew** [comment]
Please remove your access key and secret. Don't share those. You should now rotate them and expire the ones you shared.

Can you share your string from the debug and what the "the string to sign" from amazon?

**Comment by PeterTough2** [comment]
It's okay, I am using it as sandbox for now.

You can go ahead and use it to generate an access_token.

I will reset it once I figure this out.

**Comment by phpandrew** [comment]
I have updated my code, using the latest version. It's in a class now.

You can copy the functions into your existing code and see if that works for you.

**Comment by PeterTough2** [comment]
The amazon sts endpoint does not return any data, using Postman it works with my credentials above.
I think something is missing in sts request header.

When I run the code, the `/sellers/v1/marketplaceParticipations` endpoint returns this error

```
{
      "message": "The security token included in the request is invalid.",
      "code": "InvalidInput"
    }
```

Any idea what I might be missing..

**Comment by phpandrew** [comment]
The security token, or session token should get generated using your LWA credentials. Can you share the output when you generate these temporary credentials? Turn debug on.

`x-amz-security-token: '.$this->Amz_SessionToken`

This header is required to make the call to any SPAPI endpoint. 
Check to see if this security token - or the access key, security key are being generated when you run `updateCredentials()`

**Comment by PeterTough2** [comment]
It returns empty string.

When I use postman, I can generate both access_token and session_token from
their respective endpoints.

**Comment by phpandrew** [comment]
Please try the latest test.php file, this includes setting `setTokens`, using an existing SPAPI token

**Comment by PeterTough2** [comment]
I have tried it.

I want to ask, is `$awssig->setTokens("Atza|your_token_here");` same as `$awssig->setTokens("Atc|your_token_here");`

**Comment by phpandrew** [comment]
The Atza | Atzr will be the access | refresh token that you'll get when you authorize a user.

You will get these tokens when you authorize via `https://sellercentral.amazon.com/apps/authorize/consent?application_id=....` and then request it via `https://api.amazon.com/auth/o2/token`
